---
github:
  - tag: v2.5.1
    owner: fluxcd
    repo: flux2
    assets:
      - install.yaml
  - tag: v1.4.0
    owner: envoyproxy
    repo: gateway
    files:
      - charts/gateway-helm/crds/gatewayapi-crds.yaml
    dirs:
      - charts/gateway-helm/crds/generated
kubernetes:
  - version: v1.31.8
  - version: v1.31.9
  - version: v1.32.4
  - version: v1.32.5
  - version: v1.33.1